services:
  laravel-docker:
    container_name: laravel-cms-lite
    build: .
    volumes:
      - ./laravel-app:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    # ports:
    #   - 9002:9002
    restart: unless-stopped
  queue-worker:
    build: .
    command: php artisan queue:work --queue=export_blog_articles,default -v
    #command: sleep infinity
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - laravel-docker
    restart: unless-stopped
